"""Repository interface (DATA_MODEL "storage mapping").

The audit table is deliberately asymmetric: the interface offers ``append_audit``
and readers, and **no** update or delete. Append-only is enforced by the absence
of an API, not by convention (FR-12).
"""

from __future__ import annotations

from collections.abc import Iterator, Mapping
from contextlib import AbstractContextManager
from typing import Any, Protocol, runtime_checkable

from voicekin.models import (
    AuditEvent,
    AuditRecord,
    ConsentRecord,
    Delivery,
    DeviceTarget,
    EnrollmentSample,
    Instance,
    Utterance,
    VoiceProfile,
)

SCHEMA_VERSION = 1


@runtime_checkable
class Repository(Protocol):
    """Persistence for every VoiceKin entity."""

    def initialize(self) -> None: ...
    def close(self) -> None: ...
    def transaction(self) -> AbstractContextManager[None]: ...

    # instance ------------------------------------------------------------- #
    def get_instance(self) -> Instance | None: ...
    def put_instance(self, instance: Instance) -> None: ...

    # profiles ------------------------------------------------------------- #
    def get_profile(self, profile_id: str) -> VoiceProfile | None: ...
    def list_profiles(self) -> list[VoiceProfile]: ...
    def save_profile(self, profile: VoiceProfile) -> None: ...

    # enrollment samples --------------------------------------------------- #
    def save_sample(self, sample: EnrollmentSample) -> None: ...
    def get_sample(self, sample_id: str) -> EnrollmentSample | None: ...
    def list_samples(self, profile_id: str) -> list[EnrollmentSample]: ...
    def delete_sample(self, sample_id: str) -> None: ...

    # consent records ------------------------------------------------------ #
    def save_consent(self, consent: ConsentRecord) -> None: ...
    def get_consent(self, consent_id: str) -> ConsentRecord | None: ...
    def list_consents(self, profile_id: str) -> list[ConsentRecord]: ...
    def delete_consent(self, consent_id: str) -> None: ...

    # utterances ----------------------------------------------------------- #
    def save_utterance(self, utterance: Utterance) -> None: ...
    def get_utterance(self, utterance_id: str) -> Utterance | None: ...
    def list_utterances(self, profile_id: str) -> list[Utterance]: ...
    def find_utterance_by_output_sha256(self, output_sha256: str) -> Utterance | None: ...

    # deliveries ----------------------------------------------------------- #
    def save_delivery(self, delivery: Delivery) -> None: ...
    def list_deliveries(self, utterance_id: str) -> list[Delivery]: ...
    def list_profile_deliveries(self, profile_id: str) -> list[Delivery]: ...

    # device targets ------------------------------------------------------- #
    def save_target(self, target: DeviceTarget) -> None: ...
    def get_target(self, target_id: str) -> DeviceTarget | None: ...
    def list_targets(self) -> list[DeviceTarget]: ...

    # audit chain (append-only) -------------------------------------------- #
    def append_audit(
        self,
        *,
        ts: str,
        event: AuditEvent,
        profile_id: str | None = None,
        consent_id: str | None = None,
        utterance_id: str | None = None,
        detail: Mapping[str, Any] | None = None,
    ) -> AuditRecord: ...
    def audit_head(self) -> AuditRecord | None: ...
    def list_audit(self, since_seq: int = 0) -> list[AuditRecord]: ...
    def iter_audit(self) -> Iterator[AuditRecord]: ...
    def list_audit_for_utterance(self, utterance_id: str) -> list[AuditRecord]: ...


__all__ = ["SCHEMA_VERSION", "Repository"]
