"""Pure domain logic for datasweep.

Deterministic by construction: no network, no filesystem, no clock reads, no
unseeded randomness (the pipeline is in fact randomness-free).  Time enters as
data from the caller.
"""

from .models import (
    RULES,
    AuditEntry,
    AuditKind,
    CleanResult,
    ColumnProfile,
    ColumnType,
    Disposition,
    FileFormat,
    Fix,
    FixPlan,
    Issue,
    IssueClass,
    IssueSummary,
    Policy,
    Proposal,
    RawTable,
    ReviewItem,
    ReviewStatus,
    Revision,
    Run,
    RunStatus,
    RunSummary,
    SourceFile,
    Stage,
    TableProfile,
    Tier,
    TriggerKind,
    WatchedFolder,
    review_item_id,
    rule_spec,
)
from .pipeline import apply_revision, clean_table
from .report import render_report
from .transforms import apply_plan, audit_diff_mismatches, revert

__all__ = [
    "RULES",
    "AuditEntry",
    "AuditKind",
    "CleanResult",
    "ColumnProfile",
    "ColumnType",
    "Disposition",
    "FileFormat",
    "Fix",
    "FixPlan",
    "Issue",
    "IssueClass",
    "IssueSummary",
    "Policy",
    "Proposal",
    "RawTable",
    "ReviewItem",
    "ReviewStatus",
    "Revision",
    "Run",
    "RunStatus",
    "RunSummary",
    "SourceFile",
    "Stage",
    "TableProfile",
    "Tier",
    "TriggerKind",
    "WatchedFolder",
    "apply_plan",
    "apply_revision",
    "audit_diff_mismatches",
    "clean_table",
    "render_report",
    "revert",
    "review_item_id",
    "rule_spec",
]
